# Jekyll configuration for GitHub Pages

# Exclude directories and files from processing
exclude:
  - node_modules
  - functions
  - README.md
  - CHANGELOG.md
  - LICENSE
  - TODO.md
  - .github
  - .vscode
  - .firebaserc
  - firebase.json
  - firestore.indexes.json
  - firestore.rules
  - package.json
  - package-lock.json
  - "*.log"

# GitHub Pages settings
theme: jekyll-theme-primer

# Site settings
title: EU2K Hub
description: Európa 2000 Gimnázium Hub alkalmazás

# Build settings
markdown: kramdown
highlighter: rouge

# Plugin settings
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub metadata
repository: eu2kdevs/EU2K-Hub